interface Doctor {
  id: number;
  name: string;
  number: string;
  address: string;
  specialization: string;
  city: string;
  insurance: string;
}

const doctorsData: Doctor[] = [
  {
    id: 1,
    name: "Dr. Alice Smith",
    number: "555-123-4567",
    address: "123 Health St, New York, NY",
    specialization: "diabetes",
    city: "new_york",
    insurance: "aetna",
  },
  {
    id: 2,
    name: "Dr. Bob Johnson",
    number: "555-987-6543",
    address: "456 Wellness Ave, Los Angeles, CA",
    specialization: "hypertension",
    city: "los_angeles",
    insurance: "blue_cross",
  },
  {
    id: 3,
    name: "Dr. Carol White",
    number: "555-111-2222",
    address: "789 Cure Rd, Chicago, IL",
    specialization: "obesity",
    city: "chicago",
    insurance: "cigna",
  },
  {
    id: 4,
    name: "Dr. David Green",
    number: "555-333-4444",
    address: "101 Life Blvd, Houston, TX",
    specialization: "heart_disease",
    city: "houston",
    insurance: "unitedhealthcare",
  },
  {
    id: 5,
    name: "Dr. Emily Brown",
    number: "555-555-6666",
    address: "202 Serene Dr, New York, NY",
    specialization: "anxiety",
    city: "new_york",
    insurance: "blue_cross",
  },
  {
    id: 6,
    name: "Dr. Frank Black",
    number: "555-777-8888",
    address: "303 Calm Ct, Los Angeles, CA",
    specialization: "depression",
    city: "los_angeles",
    insurance: "aetna",
  },
  {
    id: 7,
    name: "Dr. Grace Lee",
    number: "555-222-3333",
    address: "888 Vitality Way, Chicago, IL",
    specialization: "diabetes",
    city: "chicago",
    insurance: "unitedhealthcare",
  },
  {
    id: 8,
    name: "Dr. Henry Wilson",
    number: "555-444-5555",
    address: "999 Peace Pl, Houston, TX",
    specialization: "hypertension",
    city: "houston",
    insurance: "cigna",
  },
  {
    id: 9,
    name: "Dr. Isabella King",
    number: "555-000-1111",
    address: "404 Fitness St, Los Angeles, CA",
    specialization: "obesity",
    city: "los_angeles",
    insurance: "aetna",
  },
  {
    id: 10,
    name: "Dr. Jack Miller",
    number: "555-111-0000",
    address: "505 Calm Rd, Houston, TX",
    specialization: "anxiety",
    city: "houston",
    insurance: "blue_cross",
  },
  {
    id: 11,
    name: "Dr. Olivia Davis",
    number: "555-333-7777",
    address: "606 Heart Ln, New York, NY",
    specialization: "heart_disease",
    city: "new_york",
    insurance: "cigna",
  },
  {
    id: 12,
    name: "Dr. Robert Clark",
    number: "555-666-9999",
    address: "707 Serenity Ave, Chicago, IL",
    specialization: "depression",
    city: "chicago",
    insurance: "unitedhealthcare",
  },
  {
    id: 13,
    name: "Dr. Sophia Lewis",
    number: "555-888-2222",
    address: "808 Health Blvd, New York, NY",
    specialization: "hypertension",
    city: "new_york",
    insurance: "aetna",
  },
  {
    id: 14,
    name: "Dr. William Green",
    number: "555-123-9876",
    address: "101 Wellness Way, Los Angeles, CA",
    specialization: "diabetes",
    city: "los_angeles",
    insurance: "cigna",
  },
  {
    id: 15,
    name: "Dr. Mia Rodriguez",
    number: "555-234-8765",
    address: "202 Calm Waters, Houston, TX",
    specialization: "obesity",
    city: "houston",
    insurance: "aetna",
  },
  {
    id: 16,
    name: "Dr. Noah Taylor",
    number: "555-345-7654",
    address: "303 Serenity St, Chicago, IL",
    specialization: "anxiety",
    city: "chicago",
    insurance: "blue_cross",
  },
  {
    id: 17,
    name: "Dr. Chloe Martinez",
    number: "555-456-6543",
    address: "404 Bright Blvd, New York, NY",
    specialization: "depression",
    city: "new_york",
    insurance: "unitedhealthcare",
  },
  {
    id: 18,
    name: "Dr. Ethan White",
    number: "555-567-5432",
    address: "505 Peaceful Pl, Los Angeles, CA",
    specialization: "heart_disease",
    city: "los_angeles",
    insurance: "aetna",
  },
  {
    id: 19,
    name: "Dr. Maya Singh",
    number: "555-987-6543",
    address: "111 Broadway, New York, NY",
    specialization: "obesity",
    city: "new_york",
    insurance: "blue_cross",
  },
  {
    id: 20,
    name: "Dr. Leo Kim",
    number: "555-121-3434",
    address: "222 Health Plaza, Chicago, IL",
    specialization: "diabetes",
    city: "chicago",
    insurance: "aetna",
  },
  {
    id: 21,
    name: "Dr. Nora Chen",
    number: "555-303-4040",
    address: "333 Evergreen Rd, Houston, TX",
    specialization: "anxiety",
    city: "houston",
    insurance: "cigna",
  },
  {
    id: 22,
    name: "Dr. Ben Carter",
    number: "555-505-6060",
    address: "444 Ocean View, Los Angeles, CA",
    specialization: "depression",
    city: "los_angeles",
    insurance: "unitedhealthcare",
  },
  {
    id: 23,
    name: "Dr. Zoe Adams",
    number: "555-707-8080",
    address: "555 Pine St, New York, NY",
    specialization: "heart_disease",
    city: "new_york",
    insurance: "aetna",
  },
  {
    id: 24,
    name: "Dr. Samira Khan",
    number: "555-909-0101",
    address: "666 Lakeview Dr, Chicago, IL",
    specialization: "hypertension",
    city: "chicago",
    insurance: "blue_cross",
  },
  {
    id: 25,
    name: "Dr. Oliver Queen",
    number: "555-111-2222",
    address: "777 Star City Rd, New York, NY",
    specialization: "depression",
    city: "new_york",
    insurance: "aetna",
  },
  {
    id: 26,
    name: "Dr. Felicity Smoak",
    number: "555-333-4444",
    address: "888 Tech Ave, Los Angeles, CA",
    specialization: "anxiety",
    city: "los_angeles",
    insurance: "unitedhealthcare",
  },
  {
    id: 27,
    name: "Dr. John Diggle",
    number: "555-555-6666",
    address: "999 Guardian Way, Houston, TX",
    specialization: "diabetes",
    city: "houston",
    insurance: "blue_cross",
  },
  {
    id: 28,
    name: "Dr. Sara Lance",
    number: "555-777-8888",
    address: "101 Waverider Blvd, Chicago, IL",
    specialization: "heart_disease",
    city: "chicago",
    insurance: "cigna",
  },
  {
    id: 29,
    name: "Dr. Ray Palmer",
    number: "555-999-0000",
    address: "202 Atom Plaza, New York, NY",
    specialization: "obesity",
    city: "new_york",
    insurance: "cigna",
  },
  {
    id: 30,
    name: "Dr. Leonard Snart",
    number: "555-010-1111",
    address: "303 Cold Ave, Los Angeles, CA",
    specialization: "hypertension",
    city: "los_angeles",
    insurance: "aetna",
  },
  {
    id: 31,
    name: "Dr. Iris West",
    number: "555-202-3030",
    address: "404 Central City Blvd, Chicago, IL",
    specialization: "diabetes",
    city: "chicago",
    insurance: "blue_cross",
  },
  {
    id: 32,
    name: "Dr. Caitlin Snow",
    number: "555-404-5050",
    address: "505 Star Labs, Houston, TX",
    specialization: "obesity",
    city: "houston",
    insurance: "unitedhealthcare",
  },
  {
    id: 33,
    name: "Dr. Barry Allen",
    number: "555-606-7070",
    address: "606 Flashpoint, New York, NY",
    specialization: "anxiety",
    city: "new_york",
    insurance: "cigna",
  },
  {
    id: 34,
    name: "Dr. Cisco Ramon",
    number: "555-808-9090",
    address: "707 Vibe St, Los Angeles, CA",
    specialization: "heart_disease",
    city: "los_angeles",
    insurance: "blue_cross",
  },
  {
    id: 35,
    name: "Dr. Harrison Wells",
    number: "555-000-1234",
    address: "808 Earth-2 Lane, Chicago, IL",
    specialization: "depression",
    city: "chicago",
    insurance: "aetna",
  },
  {
    id: 36,
    name: "Dr. Ronnie Raymond",
    number: "555-232-4545",
    address: "909 Firestorm Ave, Houston, TX",
    specialization: "hypertension",
    city: "houston",
    insurance: "aetna",
  },
  {
    id: 37,
    name: "Dr. Julian Albert",
    number: "555-676-8989",
    address: "111 Alchemy Rd, New York, NY",
    specialization: "obesity",
    city: "new_york",
    insurance: "unitedhealthcare",
  },
  {
    id: 38,
    name: "Dr. Joe West",
    number: "555-101-2020",
    address: "222 Police Dept, Los Angeles, CA",
    specialization: "diabetes",
    city: "los_angeles",
    insurance: "unitedhealthcare",
  },
  {
    id: 39,
    name: "Dr. Eobard Thawne",
    number: "555-303-4040",
    address: "333 Reverse Flash, Chicago, IL",
    specialization: "anxiety",
    city: "chicago",
    insurance: "cigna",
  },
  {
    id: 40,
    name: "Dr. Wally West",
    number: "555-505-6060",
    address: "444 Kid Flash, Houston, TX",
    specialization: "depression",
    city: "houston",
    insurance: "aetna",
  },
  {
    id: 41,
    name: "Dr. Jesse Quick",
    number: "555-707-8080",
    address: "555 Earth-3 Way, New York, NY",
    specialization: "heart_disease",
    city: "new_york",
    insurance: "blue_cross",
  },
  {
    id: 42,
    name: "Dr. Vibe",
    number: "555-909-0101",
    address: "666 Star Labs, Los Angeles, CA",
    specialization: "hypertension",
    city: "los_angeles",
    insurance: "cigna",
  },
  {
    id: 43,
    name: "Dr. Frost",
    number: "555-111-2222",
    address: "777 Cold Front, Chicago, IL",
    specialization: "obesity",
    city: "chicago",
    insurance: "blue_cross",
  },
  {
    id: 44,
    name: "Dr. Heat Wave",
    number: "555-333-4444",
    address: "888 Fire Line, Houston, TX",
    specialization: "diabetes",
    city: "houston",
    insurance: "cigna",
  },
  {
    id: 45,
    name: "Dr. Captain Cold",
    number: "555-555-6666",
    address: "999 Freeze Frame, New York, NY",
    specialization: "anxiety",
    city: "new_york",
    insurance: "aetna",
  },
  {
    id: 46,
    name: "Dr. Reverse Flash",
    number: "555-777-8888",
    address: "101 Negative Speed, Los Angeles, CA",
    specialization: "depression",
    city: "los_angeles",
    insurance: "blue_cross",
  },
  {
    id: 47,
    name: "Dr. Zoom",
    number: "555-999-0000",
    address: "202 Velocity, Chicago, IL",
    specialization: "heart_disease",
    city: "chicago",
    insurance: "unitedhealthcare",
  },
  {
    id: 48,
    name: "Dr. Savitar",
    number: "555-010-1111",
    address: "303 God of Speed, Houston, TX",
    specialization: "hypertension",
    city: "houston",
    insurance: "unitedhealthcare",
  },
];

export default doctorsData; 